Using Bootstrap code review request.
Meltrust/Using-Bootstrap pull request #4
Opened 2020-04-28 15:15 UTC by Meltrust

# In this project I:

- Built a clone from the "Newsweek" webpage using _HTML,_  _Bootstrap,_ and _CSS_.

- Added Bootstrap classes to align almost everything in order to make the page usable in devices of all sizes without the use of custom media queries.

- Put emphasis on how it behaves differently depending on the size of the screen where the website is rendered using Bootstrap breakpoints classes.

- Made extensive use of the framework.

- Built a descriptive readme for the project.

- Set up a code linter.

- Issued a descriptive pull request.

- Worked alone on this project.

### Thanks in advance for the review!  :smiley:

2020-04-28 21:19 UTC, adaorachi commented
👋 Hi @Meltrust,

Well done on the completion of the first draft of this project. You did a pretty nice job on it and I really commend that. Your images and contents are well-positioned and aligned. You made adequate use of the Bootstrap classes and also have a well-written Pull Request summary. 👍 💥 

However, there are a few changes I would want you to implement before your project can get an approval.
So, hang in there, you are just a step away from completing this project. 💪

---
### **CHANGES REQUIRED** ♻️ 
---

- [ ] Your Project view on the browser has a white trailing space by the right. The overflow occurs in the medium breakpoint between 576px and 730px. And this can be noticed with the scrolling bar highlighted in the screenshot below. Kindly fix the styling of the elements causing the overflow. 

- [ ] Also ensure your navigation bar is well padded by the sides and has less space on the top and bottom. See the screenshots below and also see the original site for better reference.

- [ ] Also ensure to include the tags at the right bottom of every image.

- [ ] The title '**More stories**' is misnamed with a different title. It should have the '**Featured Stories**' title instead. Actually, you have two titles misnamed in two different sections. Find the other misnamed title in the middle section of your project page and kindly fix them.

**Your Project Version:**

![boot1](https://user-images.githubusercontent.com/50773261/80532607-51dfad80-8994-11ea-8227-34c508bfcd5c.jpg)

**Original Version**

![boot11](https://user-images.githubusercontent.com/50773261/80532632-586e2500-8994-11ea-941c-6991f4897888.jpg)

---

- [ ] In the screenshots below, there you have the other misnamed section I mentioned in the previous comment. Kindly change it to 'More Stories', just like you have it in the original site. And thereafter adjust the image sizes and contents to look similar to the original. Attached below are screenshots for reference. Also, see the original site should you need more clarification.

**Your Project Version:**

![boot33](https://user-images.githubusercontent.com/50773261/80533137-1396be00-8995-11ea-99e2-427a44872629.jpg)

**Original Version:**
![boot3](https://user-images.githubusercontent.com/50773261/80533149-172a4500-8995-11ea-8adb-560aad3a1d60.jpg)

---

- [ ]  Here, in the small breakpoint, the '**In the magazine**' section contents should span the entire width of the page. See the screenshots below for reference. Endeavor to make reference to the original site too.

**Your Project Version**

![boot6](https://user-images.githubusercontent.com/50773261/80533559-b94a2d00-8995-11ea-8de0-cf45181cbf6a.jpg)

**Original Version:**

![boot66](https://user-images.githubusercontent.com/50773261/80533572-be0ee100-8995-11ea-8696-5c4ea7fa763c.jpg)

---

- [ ] In the section just below the '**Editor's pick**', where it has other sections of interest with titles 'US', 'WORLD', ...etc, ensure the contents are properly aligned in **small breakpoints**. The two large images should span the whole widths of the page while the aside smaller images are positioned below the larger images in a column as well. It should look similar to that of the original page.

**Your Project Version:**

![boot7](https://user-images.githubusercontent.com/50773261/80537137-6d01eb80-899b-11ea-8d62-917a24d643e4.jpg)

**Original Version** 

![boot77](https://user-images.githubusercontent.com/50773261/80537491-147f1e00-899c-11ea-918c-4e8d470c31ec.jpg)


---

- [ ] Here, the 'Culture & Travel' section should span the whole width in **small breakpoints**. Kindly view the original site for more reference.

**Your Project Version**

![boot8](https://user-images.githubusercontent.com/50773261/80537520-1e088600-899c-11ea-97af-381323f90df8.jpg)

**Original Version**

![boot88](https://user-images.githubusercontent.com/50773261/80537530-219c0d00-899c-11ea-93ee-93b581caae7f.jpg)

---

- [ ] Here, you are missing the contents below this section. It should also have more content with bordered texts.  See the highlighted area in the screenshot and also compare it to that of the original site to see differences.

**Your Project Version:**

![boot9](https://user-images.githubusercontent.com/50773261/80537623-455f5300-899c-11ea-88f8-4d47425df289.jpg)

**Original Version**

![boot99](https://user-images.githubusercontent.com/50773261/80537631-498b7080-899c-11ea-85f1-ce405d9adf98.jpg)

---

2020-04-28 21:20 UTC, adaorachi requested changes

2020-04-28 21:20 UTC, adaorachi commented on index.html
> +          <div class="px-2 bg-white text-red font-weight-bold">SUBSCRIBE ></div>
- [x] The subscription and signup buttons should contain links. So ensure they are wrapped in anchor tags.

2020-04-28 21:20 UTC, adaorachi commented on index.html
> +          <li class="position-relative">
- [x] Ensure you have your navigation bar items are links. So they should be enclosed in anchor tags.

2020-04-28 21:20 UTC, adaorachi commented on index.html
> +    <title>Newsweek - News, Analysis, Politics, Business, Technology</title>
- [ ] Here, kindly delete the commented codes. If you need to review a previous version of your code, you can make use of git history.

2020-04-28 21:23 UTC, adaorachi requested changes

2020-04-28 21:23 UTC, adaorachi commented on index.html
> +    <script
- [ ] Here, kindly delete the commented codes. If you need to review a previous version of your code, you can make use of git history.

2020-04-28 21:26 UTC, adaorachi commented
---

**The following requirements are considered OPTIONAL and so, are NOT mandatory but I will encourage you to take a moment to look into it as it will be helpful to you in this project and future ones.
NOTE: Requirements NOT marked as OPTIONAL are mandatory!**

---

2020-04-28 21:27 UTC, adaorachi commented on index.html
> +    <title>Newsweek - News, Analysis, Politics, Business, Technology</title>
- [Optional] Here it is the usual and proper convention to have your title just below the meta tags, and I would encourage you to adhere to it.

2020-04-28 21:28 UTC, adaorachi commented
### **After implementing the MANDATORY changes highlighted above, request for another review by submitting a Code Review Form.**

Should you have any questions or need any help, please feel free to reach out to me on Slack(@adaorachi). ☺️ 

**Happy Coding and Good-luck on it.**

**MaryAnn Chukwuka**

2020-04-29 12:43 UTC, Meltrust commented
Ty for the review!!! I did everything as indicated..  Requesting another code review.

2020-04-29 13:21 UTC, lekegitrepo commented
#### Hi @Meltrust :+1:
#### You did a good job :muscle: by implementing the required changes mentioned in the previous review. However, you need to fix the linter errors and also fix the consistency of the sign in and subscribe button of the navbar at the mobile screen: 425px.

**_kindly fix these and submit for review._**

### _Reviewed by Temitayo Adeleke._

2020-04-29 13:22 UTC, lekegitrepo requested changes
#### Status: Request changes.

2020-04-29 17:11 UTC, Meltrust commented
Done! (linter error was a server error according to their website).

2020-04-29 20:46 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @Meltrust, you did a great job fixing all the changes requested by the previous TSE's :+1: 
Go ahead and merge to master, do not forget to submit the project completion form.

Good luck with your next project
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

2020-04-29 22:46 UTC, merged